### ISSUE TITLE
Не добавляет чат ютуб

### ISSUE THREAD

**Issue by Hardzy** [JustOxlamon/TwoRatChat#20]
При добавлении чата с youtube пишет error 001 chanel not found, не работает на любом стриме вовсе

**Comment by Odinocka** [comment]
Суть проблемы визуально https://www.youtube.com/watch?v=Cpr7KTxhCN0&feature=youtu.be

**Comment by playerstrike** [comment]
и у меня так же

**Comment by frogost** [comment]
Очень необходимо исправление ошибки. Пробовал чат restream там тоже ошибка.

**Comment by mike2003** [comment]
Такая же фигня с этой бесполезной программой.
Короче скачал софтинку, попробовал, а тут ошибки одни и всем пофигу.
